# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(40, 50, 330, 98))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_Clear = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_Clear.setObjectName("btn_Clear")
        self.gridLayout.addWidget(self.btn_Clear, 1, 0, 1, 1)
        self.btn_PlusMinus = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_PlusMinus.setObjectName("btn_PlusMinus")
        self.gridLayout.addWidget(self.btn_PlusMinus, 1, 1, 1, 1)
        self.btn_Percent = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_Percent.setObjectName("btn_Percent")
        self.gridLayout.addWidget(self.btn_Percent, 1, 2, 1, 1)
        self.btn_Divide = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.btn_Divide.setObjectName("btn_Divide")
        self.gridLayout.addWidget(self.btn_Divide, 1, 3, 1, 1)
        self.le_WriteNum = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.le_WriteNum.setObjectName("le_WriteNum")
        self.gridLayout.addWidget(self.le_WriteNum, 0, 0, 1, 4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_Clear.setText(_translate("Form", "C"))
        self.btn_PlusMinus.setText(_translate("Form", "+/-"))
        self.btn_Percent.setText(_translate("Form", "%"))
        self.btn_Divide.setText(_translate("Form", "/"))
